title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
header1: w. h. für die Enkel
header2: Opa Wolfgang für Julika, Erik und Simon
